#!/usr/bin/env bash
# Materialize /workspace/.env from Cursor Cloud secrets (never commit .env).
# Idempotent: only writes when SECTURAFAB_CLIENT_ID and SECTURAFAB_CLIENT_SECRET are set.
set -euo pipefail
cd "$(dirname "$0")/.."

if [[ -z "${SECTURAFAB_CLIENT_ID:-}" || -z "${SECTURAFAB_CLIENT_SECRET:-}" ]]; then
  echo "cursor_cloud_write_env: SECTURAFAB_CLIENT_ID/SECRET not set — leaving .env unchanged"
  exit 0
fi

umask 077
tmp="$(mktemp)"
{
  echo "# Generated by scripts/cursor_cloud_write_env.sh from Cursor secrets"
  echo "SECTURAFAB_BASE_URL=${SECTURAFAB_BASE_URL:-https://api.secturafab.com}"
  echo "SECTURAFAB_TOKEN_URL=${SECTURAFAB_TOKEN_URL:-https://www.secturafab.com/token}"
  echo "SECTURAFAB_CLIENT_ID=${SECTURAFAB_CLIENT_ID}"
  echo "SECTURAFAB_CLIENT_SECRET=${SECTURAFAB_CLIENT_SECRET}"
  echo "SECTURAFAB_DEFAULT_MACHINE=${SECTURAFAB_DEFAULT_MACHINE:-Laser}"
  echo "SECTURAFAB_DEFAULT_MATERIAL=${SECTURAFAB_DEFAULT_MATERIAL:-A36}"
  echo "SECTURAFAB_DEFAULT_THICKNESS=${SECTURAFAB_DEFAULT_THICKNESS:-0.25}"
  echo "SECTURAFAB_ORGANIZATION=${SECTURAFAB_ORGANIZATION:-Kannon Manufacturing}"
  if [[ -n "${SECTURAFAB_USERNAME:-}" ]]; then
    echo "SECTURAFAB_USERNAME=${SECTURAFAB_USERNAME}"
  fi
  if [[ -n "${SECTURAFAB_PASSWORD:-}" ]]; then
    echo "SECTURAFAB_PASSWORD=${SECTURAFAB_PASSWORD}"
  fi
  if [[ -n "${SECTURAFAB_TENANT:-}" ]]; then
    echo "SECTURAFAB_TENANT=${SECTURAFAB_TENANT}"
  fi
} >"$tmp"
mv "$tmp" .env
echo "cursor_cloud_write_env: wrote .env from Cursor secrets"
